### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by chefpatatdev** [DNSJS/HeliosTutorials#6]
Hello, I have a question not really a Issue.
In step 3 you ask for a location for the launcher files" BASE_URL=Completez avec l'url du serveur où les fichiers du launcher seront hébergés  (exemple: https://files.dnsjs.ml/launcher/) " Does it need to be like all the files and can this be done with a github or do i need a node server with the files on it?

My discord is chefpatat#5233 , if you could help me with this : )

**Comment by DNSJS** [comment]
You need a seperate node server with nginx (recommanded). Tu as besoin d'un serveur vps externe avec nginx (recommandé). Ill be doing a video about making this program work. Je ferais une vidéo a propos de ce sujet.

**Comment by DNSJS** [comment]
Thread Closed. Contact me on Aventium Softworks for any questions regarding this thread.
